--DROP TABLE topCategories;
CREATE TABLE topCategories (category text,recurrence integer);
INSERT INTO topCategories (category,recurrence) VALUES ('180',169);
INSERT INTO topCategories (category,recurrence) VALUES ('evolutionary computation',122);
INSERT INTO topCategories (category,recurrence) VALUES ('NLP',119);
INSERT INTO topCategories (category,recurrence) VALUES ('adaptation',98);
INSERT INTO topCategories (category,recurrence) VALUES ('family history',111);
INSERT INTO topCategories (category,recurrence) VALUES ('ontologies',110);
INSERT INTO topCategories (category,recurrence) VALUES (' adaptive control',0);
INSERT INTO topCategories (category,recurrence) VALUES ('fault tolerance',106);
INSERT INTO topCategories (category,recurrence) VALUES ('ontology',93);
INSERT INTO topCategories (category,recurrence) VALUES ('aerospace',100);
INSERT INTO topCategories (category,recurrence) VALUES ('finance',125);
INSERT INTO topCategories (category,recurrence) VALUES ('open source',115);
INSERT INTO topCategories (category,recurrence) VALUES ('agents',118);
INSERT INTO topCategories (category,recurrence) VALUES ('formal methods',123);
INSERT INTO topCategories (category,recurrence) VALUES ('operating systems',98);
INSERT INTO topCategories (category,recurrence) VALUES ('agriculture',115);
INSERT INTO topCategories (category,recurrence) VALUES ('FPGA',94);
INSERT INTO topCategories (category,recurrence) VALUES ('optical',129);
INSERT INTO topCategories (category,recurrence) VALUES ('AI',124);
INSERT INTO topCategories (category,recurrence) VALUES ('fuzzy systems',101);
INSERT INTO topCategories (category,recurrence) VALUES ('optimization',100);
INSERT INTO topCategories (category,recurrence) VALUES ('algorithms',116);
INSERT INTO topCategories (category,recurrence) VALUES ('games',106);
INSERT INTO topCategories (category,recurrence) VALUES ('P2P',109);
INSERT INTO topCategories (category,recurrence) VALUES ('algorithms and bioinformatics',0);
INSERT INTO topCategories (category,recurrence) VALUES ('genealogy',102);
INSERT INTO topCategories (category,recurrence) VALUES ('parallel computing',137);
INSERT INTO topCategories (category,recurrence) VALUES ('ambient intelligence',86);
INSERT INTO topCategories (category,recurrence) VALUES ('GIS',102);
INSERT INTO topCategories (category,recurrence) VALUES ('parallel processing',86);
INSERT INTO topCategories (category,recurrence) VALUES ('antennas',93);
INSERT INTO topCategories (category,recurrence) VALUES ('graphics',210);
INSERT INTO topCategories (category,recurrence) VALUES ('parallel programming',118);
INSERT INTO topCategories (category,recurrence) VALUES ('applications',222);
INSERT INTO topCategories (category,recurrence) VALUES ('green computing',116);
INSERT INTO topCategories (category,recurrence) VALUES ('pattern recognition',104);
INSERT INTO topCategories (category,recurrence) VALUES ('architecture',480);
INSERT INTO topCategories (category,recurrence) VALUES ('grid',220);
INSERT INTO topCategories (category,recurrence) VALUES ('pedagogy',110);
INSERT INTO topCategories (category,recurrence) VALUES ('architectures',123);
INSERT INTO topCategories (category,recurrence) VALUES ('grid computing',121);
INSERT INTO topCategories (category,recurrence) VALUES ('performance',211);
INSERT INTO topCategories (category,recurrence) VALUES ('art',318);
INSERT INTO topCategories (category,recurrence) VALUES ('HCI',108);
INSERT INTO topCategories (category,recurrence) VALUES ('pervasive',225);
INSERT INTO topCategories (category,recurrence) VALUES ('artificial intelligence',95);
INSERT INTO topCategories (category,recurrence) VALUES ('health',543);
INSERT INTO topCategories (category,recurrence) VALUES ('pervasive computing',105);
INSERT INTO topCategories (category,recurrence) VALUES ('arts',104);
INSERT INTO topCategories (category,recurrence) VALUES ('health informatics',92);
INSERT INTO topCategories (category,recurrence) VALUES ('philosophy',100);
INSERT INTO topCategories (category,recurrence) VALUES ('augmented reality',102);
INSERT INTO topCategories (category,recurrence) VALUES ('healthcare',115);
INSERT INTO topCategories (category,recurrence) VALUES ('photonics',109);
INSERT INTO topCategories (category,recurrence) VALUES ('automata theory',98);
INSERT INTO topCategories (category,recurrence) VALUES ('high performance computing',104);
INSERT INTO topCategories (category,recurrence) VALUES ('physics',99);
INSERT INTO topCategories (category,recurrence) VALUES ('automatic control',116);
INSERT INTO topCategories (category,recurrence) VALUES ('history',227);
INSERT INTO topCategories (category,recurrence) VALUES ('policy',95);
INSERT INTO topCategories (category,recurrence) VALUES ('automation',210);
INSERT INTO topCategories (category,recurrence) VALUES ('human computer interaction',105);
INSERT INTO topCategories (category,recurrence) VALUES ('political science',118);
INSERT INTO topCategories (category,recurrence) VALUES ('autonomic computing',113);
INSERT INTO topCategories (category,recurrence) VALUES ('human-computer interaction',99);
INSERT INTO topCategories (category,recurrence) VALUES ('politics',119);
INSERT INTO topCategories (category,recurrence) VALUES ('big data',114);
INSERT INTO topCategories (category,recurrence) VALUES ('humanitie',113);
INSERT INTO topCategories (category,recurrence) VALUES ('power',329);
INSERT INTO topCategories (category,recurrence) VALUES ('bioinformatics',126);
INSERT INTO topCategories (category,recurrence) VALUES ('ICT',111);
INSERT INTO topCategories (category,recurrence) VALUES ('power electronics',110);
INSERT INTO topCategories (category,recurrence) VALUES ('biology',331);
INSERT INTO topCategories (category,recurrence) VALUES ('image processing',100);
INSERT INTO topCategories (category,recurrence) VALUES ('power engineering',104);
INSERT INTO topCategories (category,recurrence) VALUES ('biomedical',192);
INSERT INTO topCategories (category,recurrence) VALUES ('industrial',228);
INSERT INTO topCategories (category,recurrence) VALUES ('privacy',110);
INSERT INTO topCategories (category,recurrence) VALUES ('biomedical engineering',98);
INSERT INTO topCategories (category,recurrence) VALUES ('industrial electronics',0);
INSERT INTO topCategories (category,recurrence) VALUES ('programming',316);
INSERT INTO topCategories (category,recurrence) VALUES ('biometrics',95);
INSERT INTO topCategories (category,recurrence) VALUES ('industrial engineering',124);
INSERT INTO topCategories (category,recurrence) VALUES ('programming languages',100);
INSERT INTO topCategories (category,recurrence) VALUES ('biotechnology',108);
INSERT INTO topCategories (category,recurrence) VALUES ('industry',214);
INSERT INTO topCategories (category,recurrence) VALUES ('propagation',112);
INSERT INTO topCategories (category,recurrence) VALUES ('business',450);
INSERT INTO topCategories (category,recurrence) VALUES ('industry applications',107);
INSERT INTO topCategories (category,recurrence) VALUES ('psychology',106);
INSERT INTO topCategories (category,recurrence) VALUES ('business intelligence',103);
INSERT INTO topCategories (category,recurrence) VALUES ('informatics',313);
INSERT INTO topCategories (category,recurrence) VALUES ('radar',114);
INSERT INTO topCategories (category,recurrence) VALUES ('business management',125);
INSERT INTO topCategories (category,recurrence) VALUES ('information',1043);
INSERT INTO topCategories (category,recurrence) VALUES ('real-time',114);
INSERT INTO topCategories (category,recurrence) VALUES ('chemistry',117);
INSERT INTO topCategories (category,recurrence) VALUES ('information management',109);
INSERT INTO topCategories (category,recurrence) VALUES ('recommender systems',101);
INSERT INTO topCategories (category,recurrence) VALUES ('circuits',104);
INSERT INTO topCategories (category,recurrence) VALUES ('information retrieval',115);
INSERT INTO topCategories (category,recurrence) VALUES ('reliability',100);
INSERT INTO topCategories (category,recurrence) VALUES ('civil engineering',111);
INSERT INTO topCategories (category,recurrence) VALUES ('information science',122);
INSERT INTO topCategories (category,recurrence) VALUES ('religion',120);
INSERT INTO topCategories (category,recurrence) VALUES ('cloud',208);
INSERT INTO topCategories (category,recurrence) VALUES ('information security',96);
INSERT INTO topCategories (category,recurrence) VALUES ('remote sensing',107);
INSERT INTO topCategories (category,recurrence) VALUES ('cloud computing',114);
INSERT INTO topCategories (category,recurrence) VALUES ('information system',247);
INSERT INTO topCategories (category,recurrence) VALUES ('requirements engineering',103);
INSERT INTO topCategories (category,recurrence) VALUES ('cognitive science',117);
INSERT INTO topCategories (category,recurrence) VALUES ('information systems',129);
INSERT INTO topCategories (category,recurrence) VALUES ('research',108);
INSERT INTO topCategories (category,recurrence) VALUES ('collaboration',115);
INSERT INTO topCategories (category,recurrence) VALUES ('information technology',107);
INSERT INTO topCategories (category,recurrence) VALUES ('RFID',105);
INSERT INTO topCategories (category,recurrence) VALUES ('communication',636);
INSERT INTO topCategories (category,recurrence) VALUES ('information theory',132);
INSERT INTO topCategories (category,recurrence) VALUES ('robotics',101);
INSERT INTO topCategories (category,recurrence) VALUES ('communication',636);
INSERT INTO topCategories (category,recurrence) VALUES ('innovation',96);
INSERT INTO topCategories (category,recurrence) VALUES ('safety',94);
INSERT INTO topCategories (category,recurrence) VALUES ('compilers',92);
INSERT INTO topCategories (category,recurrence) VALUES ('instrumentation',108);
INSERT INTO topCategories (category,recurrence) VALUES ('science',1111);
INSERT INTO topCategories (category,recurrence) VALUES ('complexity',95);
INSERT INTO topCategories (category,recurrence) VALUES ('intelligent systems',105);
INSERT INTO topCategories (category,recurrence) VALUES ('security',538);
INSERT INTO topCategories (category,recurrence) VALUES ('computation theory',0);
INSERT INTO topCategories (category,recurrence) VALUES ('interaction',313);
INSERT INTO topCategories (category,recurrence) VALUES ('semantic web',114);
INSERT INTO topCategories (category,recurrence) VALUES ('computational biology',114);
INSERT INTO topCategories (category,recurrence) VALUES ('interdisciplinary',111);
INSERT INTO topCategories (category,recurrence) VALUES ('semantics',106);
INSERT INTO topCategories (category,recurrence) VALUES ('computational intelligence',106);
INSERT INTO topCategories (category,recurrence) VALUES ('internet',205);
INSERT INTO topCategories (category,recurrence) VALUES ('semiconductor',94);
INSERT INTO topCategories (category,recurrence) VALUES ('computational linguistics',112);
INSERT INTO topCategories (category,recurrence) VALUES ('internet of things',103);
INSERT INTO topCategories (category,recurrence) VALUES ('sensor networks',112);
INSERT INTO topCategories (category,recurrence) VALUES ('computer',1329);
INSERT INTO topCategories (category,recurrence) VALUES ('IR',97);
INSERT INTO topCategories (category,recurrence) VALUES ('sensors',118);
INSERT INTO topCategories (category,recurrence) VALUES ('computer architecture',116);
INSERT INTO topCategories (category,recurrence) VALUES ('IT',93);
INSERT INTO topCategories (category,recurrence) VALUES ('services',228);
INSERT INTO topCategories (category,recurrence) VALUES ('computer engineering',112);
INSERT INTO topCategories (category,recurrence) VALUES ('knowledge discovery',129);
INSERT INTO topCategories (category,recurrence) VALUES ('signal processing',118);
INSERT INTO topCategories (category,recurrence) VALUES ('computer graphics',99);
INSERT INTO topCategories (category,recurrence) VALUES ('knowledge engineering',91);
INSERT INTO topCategories (category,recurrence) VALUES ('simulation',111);
INSERT INTO topCategories (category,recurrence) VALUES ('computer networks',122);
INSERT INTO topCategories (category,recurrence) VALUES ('knowledge management',108);
INSERT INTO topCategories (category,recurrence) VALUES ('SOA',105);
INSERT INTO topCategories (category,recurrence) VALUES ('computer science',219);
INSERT INTO topCategories (category,recurrence) VALUES ('knowledge representation',112);
INSERT INTO topCategories (category,recurrence) VALUES ('social',877);
INSERT INTO topCategories (category,recurrence) VALUES ('computer security',122);
INSERT INTO topCategories (category,recurrence) VALUES ('language',312);
INSERT INTO topCategories (category,recurrence) VALUES ('social computing',118);
INSERT INTO topCategories (category,recurrence) VALUES ('computer vision',109);
INSERT INTO topCategories (category,recurrence) VALUES ('lasers',95);
INSERT INTO topCategories (category,recurrence) VALUES ('social media',102);
INSERT INTO topCategories (category,recurrence) VALUES ('computers',112);
INSERT INTO topCategories (category,recurrence) VALUES ('law',116);
INSERT INTO topCategories (category,recurrence) VALUES ('social network analysis',106);
INSERT INTO topCategories (category,recurrence) VALUES ('computing',1479);
INSERT INTO topCategories (category,recurrence) VALUES ('learning',425);
INSERT INTO topCategories (category,recurrence) VALUES ('social networks',113);
INSERT INTO topCategories (category,recurrence) VALUES ('CONFERENCE',118);
INSERT INTO topCategories (category,recurrence) VALUES ('life sciences',98);
INSERT INTO topCategories (category,recurrence) VALUES ('social science',222);
INSERT INTO topCategories (category,recurrence) VALUES ('control',340);
INSERT INTO topCategories (category,recurrence) VALUES ('linguistics',211);
INSERT INTO topCategories (category,recurrence) VALUES ('social sciences',119);
INSERT INTO topCategories (category,recurrence) VALUES ('cryptography',90);
INSERT INTO topCategories (category,recurrence) VALUES ('linked data',113);
INSERT INTO topCategories (category,recurrence) VALUES ('social web',107);
INSERT INTO topCategories (category,recurrence) VALUES ('CSCW',110);
INSERT INTO topCategories (category,recurrence) VALUES ('literature',107);
INSERT INTO topCategories (category,recurrence) VALUES ('society',97);
INSERT INTO topCategories (category,recurrence) VALUES ('cultural studies',108);
INSERT INTO topCategories (category,recurrence) VALUES ('logic',109);
INSERT INTO topCategories (category,recurrence) VALUES ('sociology',112);
INSERT INTO topCategories (category,recurrence) VALUES ('culture',217);
INSERT INTO topCategories (category,recurrence) VALUES ('logistics',110);
INSERT INTO topCategories (category,recurrence) VALUES ('soft computing',123);
INSERT INTO topCategories (category,recurrence) VALUES ('cyber security',101);
INSERT INTO topCategories (category,recurrence) VALUES ('machine learning',96);
INSERT INTO topCategories (category,recurrence) VALUES ('software',466);
INSERT INTO topCategories (category,recurrence) VALUES ('cyber-physical systems',109);
INSERT INTO topCategories (category,recurrence) VALUES ('machine translation',106);
INSERT INTO topCategories (category,recurrence) VALUES ('software architecture',116);
INSERT INTO topCategories (category,recurrence) VALUES ('cybernetics',116);
INSERT INTO topCategories (category,recurrence) VALUES ('management',665);
INSERT INTO topCategories (category,recurrence) VALUES ('software engineering',108);
INSERT INTO topCategories (category,recurrence) VALUES ('data management',98);
INSERT INTO topCategories (category,recurrence) VALUES ('manufacturing',102);
INSERT INTO topCategories (category,recurrence) VALUES ('software testing',137);
INSERT INTO topCategories (category,recurrence) VALUES ('data mining',146);
INSERT INTO topCategories (category,recurrence) VALUES ('marketing',113);
INSERT INTO topCategories (category,recurrence) VALUES ('speech',105);
INSERT INTO topCategories (category,recurrence) VALUES ('database',209);
INSERT INTO topCategories (category,recurrence) VALUES ('materials',94);
INSERT INTO topCategories (category,recurrence) VALUES ('statistics',112);
INSERT INTO topCategories (category,recurrence) VALUES ('database and data mining',0);
INSERT INTO topCategories (category,recurrence) VALUES ('mathematics',125);
INSERT INTO topCategories (category,recurrence) VALUES ('sustainability',91);
INSERT INTO topCategories (category,recurrence) VALUES ('databases',97);
INSERT INTO topCategories (category,recurrence) VALUES ('measurement',108);
INSERT INTO topCategories (category,recurrence) VALUES ('SYSTEM',104);
INSERT INTO topCategories (category,recurrence) VALUES ('dependability',97);
INSERT INTO topCategories (category,recurrence) VALUES ('mechanical',218);
INSERT INTO topCategories (category,recurrence) VALUES ('systems',1184);
INSERT INTO topCategories (category,recurrence) VALUES ('design',242);
INSERT INTO topCategories (category,recurrence) VALUES ('mechanical engineering',108);
INSERT INTO topCategories (category,recurrence) VALUES ('systems engineering',107);
INSERT INTO topCategories (category,recurrence) VALUES ('design automation',116);
INSERT INTO topCategories (category,recurrence) VALUES ('mechatronics',106);
INSERT INTO topCategories (category,recurrence) VALUES ('technologies',110);
INSERT INTO topCategories (category,recurrence) VALUES ('development',210);
INSERT INTO topCategories (category,recurrence) VALUES ('media',322);
INSERT INTO topCategories (category,recurrence) VALUES ('technology',431);
INSERT INTO topCategories (category,recurrence) VALUES ('digital libraries',99);
INSERT INTO topCategories (category,recurrence) VALUES ('medical imaging',111);
INSERT INTO topCategories (category,recurrence) VALUES ('telecommunication',218);
INSERT INTO topCategories (category,recurrence) VALUES ('distributed computing',109);
INSERT INTO topCategories (category,recurrence) VALUES ('medicine',110);
INSERT INTO topCategories (category,recurrence) VALUES ('telecommunications',105);
INSERT INTO topCategories (category,recurrence) VALUES ('distributed systems',104);
INSERT INTO topCategories (category,recurrence) VALUES ('microwave',106);
INSERT INTO topCategories (category,recurrence) VALUES ('testing',242);
INSERT INTO topCategories (category,recurrence) VALUES ('e-business',109);
INSERT INTO topCategories (category,recurrence) VALUES ('middleware',122);
INSERT INTO topCategories (category,recurrence) VALUES ('text mining',125);
INSERT INTO topCategories (category,recurrence) VALUES ('e-commerce',92);
INSERT INTO topCategories (category,recurrence) VALUES ('mobile',217);
INSERT INTO topCategories (category,recurrence) VALUES ('theoretical computer science',117);
INSERT INTO topCategories (category,recurrence) VALUES ('e-health',105);
INSERT INTO topCategories (category,recurrence) VALUES ('mobile computing',94);
INSERT INTO topCategories (category,recurrence) VALUES ('theory',349);
INSERT INTO topCategories (category,recurrence) VALUES ('e-learning',113);
INSERT INTO topCategories (category,recurrence) VALUES ('mobility',96);
INSERT INTO topCategories (category,recurrence) VALUES ('trust',95);
INSERT INTO topCategories (category,recurrence) VALUES ('economics',115);
INSERT INTO topCategories (category,recurrence) VALUES ('model-driven development',95);
INSERT INTO topCategories (category,recurrence) VALUES ('ubiquitous',237);
INSERT INTO topCategories (category,recurrence) VALUES ('education',100);
INSERT INTO topCategories (category,recurrence) VALUES ('modeling',112);
INSERT INTO topCategories (category,recurrence) VALUES ('ubiquitous computing',113);
INSERT INTO topCategories (category,recurrence) VALUES ('ehealth',107);
INSERT INTO topCategories (category,recurrence) VALUES ('modelling',121);
INSERT INTO topCategories (category,recurrence) VALUES ('USENIX',110);
INSERT INTO topCategories (category,recurrence) VALUES ('elearning',115);
INSERT INTO topCategories (category,recurrence) VALUES ('molecular biology',115);
INSERT INTO topCategories (category,recurrence) VALUES ('verification',101);
INSERT INTO topCategories (category,recurrence) VALUES ('electrical',223);
INSERT INTO topCategories (category,recurrence) VALUES ('multi-agent systems',104);
INSERT INTO topCategories (category,recurrence) VALUES ('video',126);
INSERT INTO topCategories (category,recurrence) VALUES ('electrical engineering',117);
INSERT INTO topCategories (category,recurrence) VALUES ('multimedia',111);
INSERT INTO topCategories (category,recurrence) VALUES ('virtual reality',90);
INSERT INTO topCategories (category,recurrence) VALUES ('electro-optics',0);
INSERT INTO topCategories (category,recurrence) VALUES ('musi',107);
INSERT INTO topCategories (category,recurrence) VALUES ('virtualization',102);
INSERT INTO topCategories (category,recurrence) VALUES ('electron devices',110);
INSERT INTO topCategories (category,recurrence) VALUES ('nanotechnology',116);
INSERT INTO topCategories (category,recurrence) VALUES ('visualization',124);
INSERT INTO topCategories (category,recurrence) VALUES ('electronics',219);
INSERT INTO topCategories (category,recurrence) VALUES ('natural language processing',106);
INSERT INTO topCategories (category,recurrence) VALUES ('VLSI',101);
INSERT INTO topCategories (category,recurrence) VALUES ('embedded systems',115);
INSERT INTO topCategories (category,recurrence) VALUES ('navigation',114);
INSERT INTO topCategories (category,recurrence) VALUES ('web',532);
INSERT INTO topCategories (category,recurrence) VALUES ('energy',104);
INSERT INTO topCategories (category,recurrence) VALUES ('network',1323);
INSERT INTO topCategories (category,recurrence) VALUES ('web 2.0',97);
INSERT INTO topCategories (category,recurrence) VALUES ('engineering',1408);
INSERT INTO topCategories (category,recurrence) VALUES ('network management',105);
INSERT INTO topCategories (category,recurrence) VALUES ('web services',108);
INSERT INTO topCategories (category,recurrence) VALUES ('english',127);
INSERT INTO topCategories (category,recurrence) VALUES ('network security',108);
INSERT INTO topCategories (category,recurrence) VALUES ('wireless',551);
INSERT INTO topCategories (category,recurrence) VALUES ('environment',192);
INSERT INTO topCategories (category,recurrence) VALUES ('networking',106);
INSERT INTO topCategories (category,recurrence) VALUES ('wireless communication',229);
INSERT INTO topCategories (category,recurrence) VALUES ('environmental engineering',87);
INSERT INTO topCategories (category,recurrence) VALUES ('networks',691);
INSERT INTO topCategories (category,recurrence) VALUES ('wireless communications',102);
INSERT INTO topCategories (category,recurrence) VALUES ('ethics',117);
INSERT INTO topCategories (category,recurrence) VALUES ('neural networks',113);
INSERT INTO topCategories (category,recurrence) VALUES ('wireless network',229);
INSERT INTO topCategories (category,recurrence) VALUES ('evaluation',91);
INSERT INTO topCategories (category,recurrence) VALUES ('neuroscience',102);
INSERT INTO topCategories (category,recurrence) VALUES ('wireless networks',128);
INSERT INTO topCategories (category,recurrence) VALUES ('',31736);
